[[SCIP]]
arch = "aarch64"
git-tree-sha1 = "c1d6ed6a0c149dfd914705e2076cf519aa18eead"
os = "macos"

    [[SCIP.download]]
    sha256 = "422e8f6b834e3752cb27503fee41051c7b45d6f672b795f7407f463da02f146a"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v900.200.400+0/SCIP.v900.200.400.aarch64-apple-darwin.tar.gz"
[[SCIP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "792b6cdbd2ab26963e858f995b6297250fec2cc4"
libc = "glibc"
os = "linux"

    [[SCIP.download]]
    sha256 = "712852615c515c31d02a4a7f784db33963514f6a3f45fe7d6ab161ee59f52f28"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v900.200.400+0/SCIP.v900.200.400.aarch64-linux-gnu-cxx11.tar.gz"
[[SCIP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af0a09f76c4419025be81d56c93df9f97ae480ba"
libc = "musl"
os = "linux"

    [[SCIP.download]]
    sha256 = "4eed2a0dde80a65451daf5e9495ec1f91ba783367988f6cde35bf4dd181a0e0a"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v900.200.400+0/SCIP.v900.200.400.aarch64-linux-musl-cxx11.tar.gz"
[[SCIP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ccc3515c53068b845dac5a80cef71f44c8a13c3"
libc = "glibc"
os = "linux"

    [[SCIP.download]]
    sha256 = "91d78b6be75e59b9355faefb0e7bbeacd6aebf34992278698cbdcfa1df780c00"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v900.200.400+0/SCIP.v900.200.400.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SCIP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ac99dc8d97490f8007aa22e338de9b63755e686"
libc = "musl"
os = "linux"

    [[SCIP.download]]
    sha256 = "be31aecc6455b72ba136e2a9d3d5af110d29e2eaf71549a5c08b82adae5b71ba"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v900.200.400+0/SCIP.v900.200.400.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SCIP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a0a13ac389f975210d77f319549718a39b7b8c6"
libc = "glibc"
os = "linux"

    [[SCIP.download]]
    sha256 = "432a7fdff349d89830566ed0737b9d41c8c3f8cea071f41f5f52e793d9b00af1"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v900.200.400+0/SCIP.v900.200.400.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SCIP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "545e72f8652279e1c80c1477f2a3e5e772d2bd20"
libc = "musl"
os = "linux"

    [[SCIP.download]]
    sha256 = "919c15622e0a1d210dbf5c4c60bfcaae492870266a76c543e41f4f5986ecf4eb"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v900.200.400+0/SCIP.v900.200.400.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SCIP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81af9ff5f64d5c1cb82876a1bec8ad7a230547fb"
libc = "glibc"
os = "linux"

    [[SCIP.download]]
    sha256 = "c477fe58c35ccb2029f70a9b479e721976fcd3cc1a4d93000c7a291fa4b1e53b"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v900.200.400+0/SCIP.v900.200.400.i686-linux-gnu-cxx11.tar.gz"
[[SCIP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ca2c6ca96eede9bb4ad5b110ef175853f296724"
libc = "musl"
os = "linux"

    [[SCIP.download]]
    sha256 = "fa0f7de3684b056b0c3f3b4459e56b7447387516379e7e1432e1d2b8ad8dac8d"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v900.200.400+0/SCIP.v900.200.400.i686-linux-musl-cxx11.tar.gz"
[[SCIP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8185ee8e67d730d0d2d1fbd02f1debd2512466d"
os = "windows"

    [[SCIP.download]]
    sha256 = "545cc750c6c12f341ad16363a8341f1033bc07b82baeeb521b8437c877684562"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v900.200.400+0/SCIP.v900.200.400.i686-w64-mingw32-cxx11.tar.gz"
[[SCIP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b726449dc76d4115f2b3503d29bd810e5db075bb"
libc = "glibc"
os = "linux"

    [[SCIP.download]]
    sha256 = "1f024b40437c37e2cd5b732b0e222f222135627fac8d94678f6bdcf36e5932e9"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v900.200.400+0/SCIP.v900.200.400.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SCIP]]
arch = "x86_64"
git-tree-sha1 = "2c88b4e1de0d6ebedd7a3e025114076adc6aca09"
os = "macos"

    [[SCIP.download]]
    sha256 = "e8c974f3f24fdb5c460e67cd6f572f1c7b711551f7bed0d9d35fe20c0430efa2"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v900.200.400+0/SCIP.v900.200.400.x86_64-apple-darwin.tar.gz"
[[SCIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5009d36d9c6ac9ecff0476d59e2f023c817e357"
libc = "glibc"
os = "linux"

    [[SCIP.download]]
    sha256 = "29cb62ad6dbac9ae5814ced66f96739533677234ed4c0f7362f74584e0d2d75b"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v900.200.400+0/SCIP.v900.200.400.x86_64-linux-gnu-cxx11.tar.gz"
[[SCIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17a7275867a8bf206a49acf11ff4a738ea73bc79"
libc = "musl"
os = "linux"

    [[SCIP.download]]
    sha256 = "14dae0cd81937bc0185d83c9f256953b02078fc6c718638d004ca503a4a59d8b"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v900.200.400+0/SCIP.v900.200.400.x86_64-linux-musl-cxx11.tar.gz"
[[SCIP]]
arch = "x86_64"
git-tree-sha1 = "60b395310438e106967165854a330a94bb2db548"
os = "freebsd"

    [[SCIP.download]]
    sha256 = "a74e6cacb15bd0f23555776894de30417c771ddad6e404261ee471d1eb7ae479"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v900.200.400+0/SCIP.v900.200.400.x86_64-unknown-freebsd.tar.gz"
[[SCIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e1718314fce219c54a041c4726569b340348c2c"
os = "windows"

    [[SCIP.download]]
    sha256 = "d931c9d6b8ffdb52169e51c69db9d2ba64980202d1a71afca26964f2abf29faf"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v900.200.400+0/SCIP.v900.200.400.x86_64-w64-mingw32-cxx11.tar.gz"
