[[SCIP]]
arch = "aarch64"
git-tree-sha1 = "8a6fd7f324e6befdb44e66fb861b5cf0a3fe5d5a"
os = "macos"

    [[SCIP.download]]
    sha256 = "bd5297d734bd4c1dce2cef83524af74a76f327871e08e55141ed19f3e10f5b28"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.aarch64-apple-darwin.tar.gz"
[[SCIP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64591cfe2de8d421b78caf851117b1de18dd6b5d"
libc = "glibc"
os = "linux"

    [[SCIP.download]]
    sha256 = "62b0338d11990ee5d255aa9b48ff8c9d78a21146092cf395d25437091e3c4a1e"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SCIP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0802e3fe35587acdf91f977999506544e7838a91"
libc = "musl"
os = "linux"

    [[SCIP.download]]
    sha256 = "c8ac6426a69271c661d509139185363f5e5b255de65ce8c212c214942a6fce92"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[SCIP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41729ec81ca564fbe12962f73734382ebd268c18"
libc = "glibc"
os = "linux"

    [[SCIP.download]]
    sha256 = "b87d81543120d762bd42a5c181c37aec9282704ca5bce6f84fd622f0b083cc51"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SCIP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1ebb83817fdf71faf59b2765af400eaf394f155"
libc = "musl"
os = "linux"

    [[SCIP.download]]
    sha256 = "607b2fda926c6324832853c0c0c7f2bc14f691073421bbf5b1ce35f8fc6770f3"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SCIP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e814c154db83681ec1b67be6d00777afe36205c1"
libc = "glibc"
os = "linux"

    [[SCIP.download]]
    sha256 = "1b7095835eb284e03a2de887f47f3ebae37538ad183c838bea896e61ac974d0c"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SCIP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41ad23906b167f3b072646fa6f428ad61959b7b0"
libc = "musl"
os = "linux"

    [[SCIP.download]]
    sha256 = "8633aea9a131d8b2cb5c8e3268152f683e6efca5d8fdcb3e197841591e575ea1"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SCIP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "365f85741c14e7e80ace9ae3d78a892c1268ff89"
libc = "glibc"
os = "linux"

    [[SCIP.download]]
    sha256 = "d934df8893ed5f4e2af42efa007a6873fd1ff68a98697777e2aef33016d94618"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.i686-linux-gnu-cxx11.tar.gz"
[[SCIP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31095165c44e8330280eef079d1674c572aa074c"
libc = "musl"
os = "linux"

    [[SCIP.download]]
    sha256 = "2b2354c7d748f0da7d72f85fe06b46a5b246100e07b5a75c265eefedbd4a1424"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.i686-linux-musl-cxx11.tar.gz"
[[SCIP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c95a7bc25e04d2bd28c05549745b9f33b7d5dc6c"
os = "windows"

    [[SCIP.download]]
    sha256 = "cc9f0e8144b6e37f112fb3194c916baf87c884de8b82bfd96f18b261e8dd50e6"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[SCIP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a98022e9a74da12fe47cd4e42342c188bfed7f8d"
libc = "glibc"
os = "linux"

    [[SCIP.download]]
    sha256 = "ce90147b129326c3af7f8a2655e66da924e5b7229e31b538469f1ee02258e98d"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SCIP]]
arch = "x86_64"
git-tree-sha1 = "8917bc508293788019e6bb16db49b1efb8519760"
os = "macos"

    [[SCIP.download]]
    sha256 = "5e98be6dee7f9dca18933a3506fdf68b11c0a8d723b8e7dcf70efeba993a47c9"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.x86_64-apple-darwin.tar.gz"
[[SCIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "911637e064b34f98bf1826677ea68a8b1818ebff"
libc = "glibc"
os = "linux"

    [[SCIP.download]]
    sha256 = "df54ef8bde3e0d82f6b8398620fd047239ca0c81f42947fbee86464a8aaa9bec"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SCIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a15234ee740b3ed1ed17f12136ef98dbfed6ec02"
libc = "musl"
os = "linux"

    [[SCIP.download]]
    sha256 = "a6550265a45a108d8eb1bbf3597e7e9566c12ed0734b4daf9ddcc4b55132b677"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[SCIP]]
arch = "x86_64"
git-tree-sha1 = "4d1b1f082c48fb1aec6ed256e337f074df64b079"
os = "freebsd"

    [[SCIP.download]]
    sha256 = "b010f7af5cef72c224a03a03ae2779c392f1ad12da56116e59db4356780f7d2b"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.x86_64-unknown-freebsd.tar.gz"
[[SCIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "396122b305c1d509ea9abd59bf29a348d5d4f1ff"
os = "windows"

    [[SCIP.download]]
    sha256 = "86aab4d90ef18118ee7f815c6c0b7c42b980a56efbd2ee7d03192c83b6374bbc"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
