[[SCIP]]
arch = "aarch64"
git-tree-sha1 = "2847d540e9808a450f7716ee33a0831a4c62d3af"
os = "macos"

    [[SCIP.download]]
    sha256 = "f2fb3ab5c1085dad5e3854786fd7f0ecf648a36b739e34554fd8eefde8133158"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.aarch64-apple-darwin.tar.gz"
[[SCIP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d4b755174d97889dbf6be4a6cad5a0cf246bd7c"
libc = "glibc"
os = "linux"

    [[SCIP.download]]
    sha256 = "741a77a612b0c5ca2ebd45c6ac8f2d5bab6d841327b3f03b4c0ab430a11ff4f5"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SCIP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1fb36ab245c76d51c70c261a3ef40d01d28ea4e0"
libc = "musl"
os = "linux"

    [[SCIP.download]]
    sha256 = "7e3d48b00f1605d17a47f9a7f1c8f926945d99104c866bc6e6f4dada797adbaa"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[SCIP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "365e3568462c3247d07a5c06422adaf6cf440cd6"
libc = "glibc"
os = "linux"

    [[SCIP.download]]
    sha256 = "a0380dd4519842601b1428cdd9aa46c80044a613a9022b1f8de18d58d9297e2b"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SCIP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0c83bd13b99558e9777ca03ccc3ed1c3363ec62"
libc = "musl"
os = "linux"

    [[SCIP.download]]
    sha256 = "378f695747ab71356154768c5036b5420f25ab58486157a73d45258e95a41600"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SCIP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "086c4e918ed1adb9865f501cabcba387e1d6cf59"
libc = "glibc"
os = "linux"

    [[SCIP.download]]
    sha256 = "66bcb579080f5edfceafff8c7d40f781934600ef97f22e8586374f3bbeaf3239"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SCIP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8a679a4fb01094c3366405901eeaf3a0156f72d"
libc = "musl"
os = "linux"

    [[SCIP.download]]
    sha256 = "e8fc91f4a4aed21e30295a6cda9fecdcf8cab1ebf357e74c6ac8469d1e8b3dc2"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SCIP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ac076a221f76ae54d63b633ab80e38c74e6338e"
libc = "glibc"
os = "linux"

    [[SCIP.download]]
    sha256 = "66f4443a338a4a6302c421d1b82970c38755da63d5bd141b23744e1aaa341b25"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.i686-linux-gnu-cxx11.tar.gz"
[[SCIP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b69a48491725e89851eb0a4503a42041f68b872a"
libc = "musl"
os = "linux"

    [[SCIP.download]]
    sha256 = "a18061651b23200d3ce8a37e9f78daa6f311a3ddc67a5dd8442be99f54c7a9e7"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.i686-linux-musl-cxx11.tar.gz"
[[SCIP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80a4499657dceb0841da52e5260797eea3c19f9e"
os = "windows"

    [[SCIP.download]]
    sha256 = "0b4a8e70a598426154eeafc07f4b6aeb33ef82c8eae20040dbcebdfa54404bbf"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[SCIP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb7a84e8d71a8e97772fb945bc51528b1657f6ac"
libc = "glibc"
os = "linux"

    [[SCIP.download]]
    sha256 = "3dd188ee5468b53e7670eaaf2ab72024dbaa60786d411bb27fbab8cc60fb2539"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SCIP]]
arch = "x86_64"
git-tree-sha1 = "7ed74a0adc8de745c0d7c625f4439ba01d5b8200"
os = "macos"

    [[SCIP.download]]
    sha256 = "cfcb3ac7da0a093eb5050af7f9006bda53e360b42a8ff2e71f9307db6909ac4f"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.x86_64-apple-darwin.tar.gz"
[[SCIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ae3cdde12fe9ba7764bea10af5b88c6045866b0"
libc = "glibc"
os = "linux"

    [[SCIP.download]]
    sha256 = "d4420e43d1abd855003a9d7532fc398a6556e3dbb9f995bd06262926fd5024e3"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SCIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ec6a5744c996f3743fe056a5ae66471de3c7d1a"
libc = "musl"
os = "linux"

    [[SCIP.download]]
    sha256 = "57606312e495ac1da7aeaf4903a2793cf01a21e9845df48c67757740dd71ef3f"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[SCIP]]
arch = "x86_64"
git-tree-sha1 = "29a328028397ff9bc30ac9f311dccb69d493e198"
os = "freebsd"

    [[SCIP.download]]
    sha256 = "da37248894f924f2f6a0075a2877c67b70450610733410266520c450991fdb4d"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.x86_64-unknown-freebsd.tar.gz"
[[SCIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07527a06f51cec5b13bbbc81cd7f8e5bf9384f83"
os = "windows"

    [[SCIP.download]]
    sha256 = "ba09a6779f2826db179326e6908ad9e5c007c3bfeceb11a8ad19e1c814548243"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_jll.jl/releases/download/SCIP-v1000.0.0+0/SCIP.v1000.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
