name = "SCIP_jll"
uuid = "e5ac4fe4-a920-5659-9bf8-f9f73e9e79ce"
version = "1000.0.0+0"

[deps]
GMP_jll = "781609d7-10c4-51f6-84f2-b8444358ff6d"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MPFR_jll = "3a97d323-0669-5f0c-9066-3539efd106a3"
Ipopt_jll = "9cc047cb-c261-5740-88fc-0cf96f7bdcc7"
boost_jll = "28df3c45-c428-5900-9ff8-a3135698ca75"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Bzip2_jll = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Readline_jll = "05236dd9-4125-5232-aa7c-9ec0c9b2c25a"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
MPFR_jll = "4.2.0"
Bzip2_jll = "1.0.9"
Ipopt_jll = "300.1400.1900"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
boost_jll = "=1.87.0"
